/*
 * generated by Xtext 2.25.0
 */
package science.robbert;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TardisLStandaloneSetup extends TardisLStandaloneSetupGenerated {

	public static void doSetup() {
		new TardisLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
